
import type { Tool } from './types';

export const MOCK_TOOLS: Tool[] = [
  {
    id: 't1',
    name: 'ImageForge AI',
    category: 'Image Generation',
    subcategory: 'Text-to-Image',
    description: 'High-quality text-to-image model with custom styles and API access for developers and artists.',
    pricing: 'Freemium',
    url: 'https://example.com/imageforge',
    affiliate: true,
    rating: 4.8,
    tags: ['text-to-image', 'api', 'designer', 'art'],
    approved: true,
  },
  {
    id: 't2',
    name: 'WriteFlow Pro',
    category: 'Writing',
    subcategory: 'Longform Content',
    description: 'AI writing assistant for marketers with advanced SEO integrations and plagiarism checks.',
    pricing: 'Paid',
    url: 'https://example.com/writeflow',
    affiliate: true,
    rating: 4.5,
    tags: ['seo', 'marketing', 'copywriting'],
    approved: true,
  },
  {
    id: 't3',
    name: 'CodeCompanion',
    category: 'Coding',
    subcategory: 'Code Generation',
    description: 'An AI pair programmer that helps you write better code faster, with support for over 20 languages.',
    pricing: 'Freemium',
    url: 'https://example.com/codecompanion',
    affiliate: false,
    rating: 4.9,
    tags: ['developer', 'vscode', 'python', 'javascript'],
    approved: true,
  },
  {
    id: 't4',
    name: 'TaskMaster AI',
    category: 'Productivity',
    subcategory: 'Project Management',
    description: 'Automate your project workflows, assign tasks, and predict project timelines with AI.',
    pricing: 'Paid',
    url: 'https://example.com/taskmaster',
    affiliate: true,
    rating: 4.3,
    tags: ['project management', 'automation', 'teams'],
    approved: true,
  },
  {
    id: 't5',
    name: 'VideoSynth',
    category: 'Video',
    subcategory: 'AI Video Editing',
    description: 'Create and edit professional videos from text prompts. Includes AI avatars and voiceovers.',
    pricing: 'Freemium',
    url: 'https://example.com/videosynth',
    affiliate: false,
    rating: 4.6,
    tags: ['video editing', 'avatars', 'social media'],
    approved: true,
  },
  {
    id: 't6',
    name: 'EchoWave',
    category: 'Audio',
    subcategory: 'Text-to-Speech',
    description: 'Ultra-realistic text-to-speech and voice cloning for creators and developers.',
    pricing: 'Paid',
    url: 'https://example.com/echowave',
    affiliate: true,
    rating: 4.7,
    tags: ['tts', 'voice cloning', 'podcasting'],
    approved: true,
  },
  {
    id: 't7',
    name: 'PixelPerfect',
    category: 'Image Generation',
    subcategory: 'Image Upscaling',
    description: 'Upscale and enhance your images without losing quality using advanced AI algorithms.',
    pricing: 'Freemium',
    url: 'https://example.com/pixelperfect',
    affiliate: false,
    rating: 4.4,
    tags: ['image editing', 'upscaling', 'photography'],
    approved: true,
  },
  {
    id: 't8',
    name: 'DraftGenius',
    category: 'Writing',
    subcategory: 'Email Assistant',
    description: 'Write better emails faster. AI-powered suggestions, tone analysis, and summarization for your inbox.',
    pricing: 'Freemium',
    url: 'https://example.com/draftgenius',
    affiliate: false,
    rating: 4.2,
    tags: ['email', 'productivity', 'communication'],
    approved: true,
  },
];

export const CATEGORIES: string[] = [
  'All',
  'Image Generation',
  'Writing',
  'Coding',
  'Productivity',
  'Video',
  'Audio',
  'Marketing',
  'Business'
];
